### ISSUE TITLE
Broadcasting

### ISSUE THREAD

**Issue by erikkaplun** [LogtalkDotOrg/logtalk3#139]
Not a bug report, but if broadcasting means sending a single message to many recipients, then why does Logtalk call sending multiple messages to a single recipient broadcasting and not flooding or batching or something more precise?

**Comment by pmoura** [comment]
History. Long ago, at the beginning of Logtalk development, the idea was to implement both the current functionality and the broadcasting control constructs found in earlier object-oriented logic programming systems like L&O and Prolog++. The same documentation section was expected to describe both functionality. But for several reasons, only the current functionality is available today.

**Comment by erikkaplun** [comment]
What is the systemic reason for the lack of broadcasting functionality in today's version of Logtalk?

**Comment by pmoura** [comment]
Bottom line, never had a real world use case for it.
