### ISSUE TITLE
Cannot clone logtalk, no correct access rights

### ISSUE THREAD

**Issue by UWN** [LogtalkDotOrg/logtalk3#144]
In response to [this](https://github.com/trealla-prolog/trealla/issues/532#issuecomment-1096560896):

```
ulrich@p0:~$ cd /opt/gupu/
ulrich@p0:/opt/gupu$ git clone git@github.com:LogtalkDotOrg/logtalk3.git
Cloning into 'logtalk3'...
The authenticity of host 'github.com (140.82.121.4)' can't be established.
ECDSA key fingerprint is 7b:99:81:1e:4c:91:a5:0d:5a:2e:2e:80:13:3f:24:ca.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'github.com,140.82.121.4' (ECDSA) to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
ulrich@p0:/opt/gupu$ 
```

**Comment by pmoura** [comment]
Nothing to do with the Logtalk repo. You're trying to clone using a SSH URL, which requires creation of an SSH key pair on your computer and adding the public key to your GitHub account. Use the HTTPS cloning URL instead.

**Comment by pmoura** [comment]
See also https://docs.github.com/en/repositories/creating-and-managing-repositories/troubleshooting-cloning-errors

**Comment by UWN** [comment]
Thank you! The interface must have changed since last time I cloned. Yes, it was too obvious for me...
