### ISSUE TITLE
list_to_set/2 is not required to order

### ISSUE THREAD

**Issue by Jean-Luc-Picard-2021** [LogtalkDotOrg/logtalk3#150]
I find a commit comment:
```
diff --git a/ports/fcube/fcube.lgt b/ports/fcube/fcube.lgt
index acdc0ebbf5..d1d46b5951 100644
--- a/ports/fcube/fcube.lgt
+++ b/ports/fcube/fcube.lgt
+ % Paulo Moura: added the next list_to_set/2 to allow using an ordered set representation
list_to_set(NewSet0, NewSet).
```
`list_to_set/2` does not order, only deduplicate.
You can try yourself in SWI-Prolog:
```
/* SWI-Prolog 8.5.14 */
?- list_to_set([c,a,b,a], X).
X = [c, a, b].
/* Its not ordered, if it were ordered it were [a,b,c] */
```
In some Prolog systems it does order, but this
is not a guarantee neither a requirement.

**Comment by Jean-Luc-Picard-2021** [comment]
If you would like to use ordered sets, you need
to use the ISO core standard sort/2.
But its not guaranteed to run faster in any way.

It can also run slower. It would only run
faster if you could eliminate the sort/2. Which
is sometimes possible, like the result of

a ord_XXX operation, doesn't need a sort/2. 


You see here, its not list_to_set/2, but list_to_ord_set/2,

list_to_ord_set(+List, -OrdSet)
Transform a list into an ordered set. This is the same as sorting the list.

It has this implementation:

list_to_ord_set(List, Set) :-
 sort(List, Set).

**Comment by pmoura** [comment]
In the same `fcube.lgt` file:

```logtalk
	:- uses(set, [
		as_set/2 as list_to_set/2, intersection/3, subtract/3, union/3
	]).
```

The Logtalk `sets` library is an ordered sets library.

**Comment by pmoura** [comment]
Union, intersection, ... are **set** operations. Subtract is not.

**Comment by Jean-Luc-Picard-2021** [comment]
What do you mean are subtract is no set operation? I find it also in set.lgt:
```
subtract(Set, [], Set) :- !.
	subtract([], _, []) :- !.
	subtract([Head1| Tail1], [Head2| Tail2], Difference) :-
		compare(Order, Head1, Head2),
		subtract(Order, Head1, Tail1, Head2, Tail2, Difference).

	subtract(=, _, Tail1, _, Tail2, Difference) :-
		subtract(Tail1, Tail2, Difference).
	subtract(<, Head1, Tail1, Head2, Tail2, [Head1| Difference]) :-
		subtract(Tail1, [Head2| Tail2], Difference).
	subtract(>, Head1, Tail1, _, Tail2, Difference) :-
subtract([Head1| Tail1], Tail2, Difference).
```
