### ISSUE TITLE
SWI-Prolog 8.5.16 Windows regression: `nul` no longer understood by the `open/3-4` predicates

### ISSUE THREAD

**Issue by pmoura** [LogtalkDotOrg/logtalk3#153]
The SWI-Prolog 8.5.16 Windows version have a regression that breaks key libraries and a large number of tests: `nul`is  no longer understood by the `open/3-4` predicates. This bug is not present in the previous version (8.5.15). If you're using running Logtalk with SWI-Prolog on Windows, avoid upgrading to version 8.5.16 and look for a possible fix in the next versions.

**Comment by JanWielemaker** [comment]
Thanks.  I see.   We can't use the "\\?\" prefix to get support for long file paths for the Windows "special" files :cry: 

P.s. Is it an option to use `open_null_stream/1` (inherited from Quintus, no clue how widely used it is).

**Comment by JanWielemaker** [comment]
Should be ok with SWI-Prolog/swipl-devel@1b9ec8d1cdcdafad37514e0c2e826fc60a26345d

**Comment by pmoura** [comment]
> P.s. Is it an option to use `open_null_stream/1` (inherited from Quintus, no clue how widely used it is)?

Possible, yes. But would require use of conditional compilation directives in multiple places.

Thanks for the quick fix. I will try it when the next nightly build for the Windows binary installer become available.

Note that you can run Logtalk distribution tests automated on Windows using the provided `scripts/logtalk_tester.ps1` PowerShell script. That would have readily flagged this regression.

**Comment by pmoura** [comment]
Fix confirmed using the `swipl-w64-2022-09-08.exe` [nightly build](https://www.swi-prolog.org/download/daily/bin/).
