### ISSUE TITLE
improving Prolog test speed for gprolog 

### ISSUE THREAD

**Issue by didoudiaz** [LogtalkDotOrg/logtalk3#168]
The Prolog test suis (tests/prolog) is not very fast for gprolog. Indeed, compiling/consulting Logtalk’s large Prolog files is not very fast in gprolog (mainly due to file IO since generated files are plain Prolog text files - something I plan to improve). It seems that these files are consulted at each test. Currently, on my M2 Mac:

```
% 186 test sets: 175 completed, 9 skipped, 2 broken, 0 timedout, 0 crashed
% 3138 tests: 97 skipped, 2918 passed, 123 failed (0 flaky)
real	5m16.638s
user	4m30.196s
sys	0m38.063s
```

Maybe it is possible to modify Logtalk to run several tests in the same session (e.g. all tests in the same directory ?). However, I understand this is maybe a major change in your code.

There are 2 other possibilities for gprolog which needs few modifications in Logtalk: compilation for byte-code and compilation to native code. 

### Preliminary step: create `integration/logtalk_gp_new.pl`

Both solutions require an initial modification in the integration file to replace the `initialization/1` directive (consisting of several `consult/1`) by `include/1` directives. This is an improvement and could be applied to all other ISO systems.

NB: I call this file `logtalk_gp_new.pl` but it is not necessary to have 2 files, simply replace the current `logtalk_gp.pl` by this content:

```
:- set_prolog_flag(suspicious_warning, off).
:- include('$LOGTALKHOME/integration/logtalk_comp_gp.pl').
:- include('$LOGTALKHOME/adapters/gnu.pl').
:- include('$LOGTALKHOME/paths/paths.pl').
:- set_prolog_flag(suspicious_warning, on).
```
NB2: I had to put the `include('logtalk_comp_gp.pl')` first (while it is consulted last), else I had a compilation warning:

```
In file included from logtalk_gp_new.pl:29
                 from $LOGTALKHOME/integration/logtalk_comp_gp.pl:26
$LOGTALKHOME/core/core.pl:191: warning: directive occurs after definition of logtalk_library_path/2 - directive ignored
```

To test with this `logtalk_gp_new.pl` (before replacing existing `logtalk_gp.pl`), modify `gplgt.sh`: 

```
#exec gprolog --entry-goal "['\$LOGTALKHOME/integration/logtalk_gp.pl']" "$@"
exec gprolog --entry-goal "['\$LOGTALKHOME/integration/logtalk_gp_new.pl']" "$@"
```

With this inclusions all tests work well (i.e. as previously and with same timing).

### Solution 1: compile for byte-code

This can be done with:
```
gplc -w logtalk_gp_new.pl
```
This creates a file `logtalk_gp_new.wbc` which can be loaded with `load/1` built-in.

Modify `gplgt.sh` replacing `consult/1` by `load/1`:

```
#exec gprolog --entry-goal "['\$LOGTALKHOME/integration/logtalk_gp.pl']" "$@"
#exec gprolog --entry-goal "['\$LOGTALKHOME/integration/logtalk_gp_new.pl']" "$@"
exec gprolog --entry-goal "load('\$LOGTALKHOME/integration/logtalk_gp_new.wbc')" "$@"
```
With this, the whole test is around 33% faster: 

```
% 186 test sets: 175 completed, 9 skipped, 2 broken, 0 timedout, 0 crashed
% 3138 tests: 97 skipped, 2918 passed, 123 failed (0 flaky)
real	3m33.545s
user	2m51.542s
sys	0m34.623s
```

### Solution 2: compile to native-code

A new top-level called `gplgt_native` including logtalk code should be obtained with:
```
gplc -o gplgt_native --new-top-level logtalk_gp_new.pl
```
But this reveals a problem: 
```
Undefined symbols for architecture arm64:
  "predicate('$logtalk#0.print_message#3'/4)", referenced from:
```
It seems that `'$logtalk#0.print_message#3'/4` is created in a temporary file/folder (I could not find its definition with grep, I only found it is invoked in `core/core.pl`). I fixed it by surrounding the 2 invocations in `core.pl` with `call/1`:
```
619c619
< 	'$logtalk#0.print_message#3'(comment(debugging), debugger, logtalk_debugger_aborted, ExCtx).
---
> 	call('$logtalk#0.print_message#3'(comment(debugging), debugger, logtalk_debugger_aborted, ExCtx)).
6729c6729
< 		'$logtalk#0.print_message#3'(Kind, core, Message, ExCtx)
---
> 		call('$logtalk#0.print_message#3'(Kind, core, Message, ExCtx))
```
The compilation is now OK:
```
gplc -o gplgt_native --new-top-level logtalk_gp_new.pl
```
NB: I suppose the adequate way to solve this is to add a `multifile/1` directive in `core.pl` (easy) but also in the temporary file created in `scratch/` (more difficult for me):
```
:- multifile('$logtalk#0.print_message#3'/4).
```
Anyway, this creates a new top-level, run it with:
```
./gplgt_native
```
This file should act exactly as `gplgt.sh`, so we can now modify `gplgt.sh` as follows:
```
#exec gprolog --entry-goal "['\$LOGTALKHOME/integration/logtalk_gp.pl']" "$@"
#exec gprolog --entry-goal "['\$LOGTALKHOME/integration/logtalk_gp_new.pl']" "$@"
#exec gprolog --entry-goal "load('\$LOGTALKHOME/integration/logtalk_gp_new.wbc')" "$@"
exec "$LOGTALKHOME/integration/gplgt_native" "$@"
```
With this, the whole test time is divided by 2:

```
% 186 test sets: 175 completed, 9 skipped, 2 broken, 0 timedout, 0 crashed
% 3138 tests: 97 skipped, 2918 passed, 123 failed (0 flaky)
real	2m55.230s
user	2m18.015s
sys	0m30.221s
```
### Conclusion

It is easy to improve, logtalk for gprolog (the inclusion vs consult can be done for other systems). I would be in favor of let the user chose which version it wants, e.g. modifying the script `gplgt.sh` to accept an additional argument (default=consult or `bc`for byte-code or `nc` for native code). Another possibility is to proved 3 scripts. 

Then modify `logtalk_tester.sh` to accept one of the 3 above (e.g. `-p gnu`, `-p gnu_bc`, `-p gnu_nc` or any other option).

**Comment by pmoura** [comment]
Detailed reply later. Meanwhile, have you noticed:

https://github.com/LogtalkDotOrg/logtalk3/tree/master/scripts/embedding/gprolog

**Comment by pmoura** [comment]
> The Prolog test suis (tests/prolog) is not very fast for gprolog. Indeed, compiling/consulting Logtalk’s large Prolog files is not very fast in gprolog (mainly due to file IO since generated files are plain Prolog text files - something I plan to improve). It seems that these files are consulted at each test. Currently, on my M2 Mac:
> 
> ```
> % 186 test sets: 175 completed, 9 skipped, 2 broken, 0 timedout, 0 crashed
> % 3138 tests: 97 skipped, 2918 passed, 123 failed (0 flaky)
> real	5m16.638s
> user	4m30.196s
> sys	0m38.063s
> ```
> 
> Maybe it is possible to modify Logtalk to run several tests in the same session (e.g. all tests in the same directory ?). However, I understand this is maybe a major change in your code.

That's already the case: each **test set** is in its own directory. I assume you meant all tests in a directory **and**  it's sub-directories?

> There are 2 other possibilities for gprolog which needs few modifications in Logtalk: compilation for byte-code and compilation to native code.
> 
> ### Preliminary step: create `integration/logtalk_gp_new.pl`
> Both solutions require an initial modification in the integration file to replace the `initialization/1` directive (consisting of several `consult/1`) by `include/1` directives. This is an improvement and could be applied to all other ISO systems.

Nowadays, yes. But, in general, consulting, ensure loading, or including files shouldn't make a significant difference in Logtalk startup times.

> NB: I call this file `logtalk_gp_new.pl` but it is not necessary to have 2 files, simply replace the current `logtalk_gp.pl` by this content:
> 
> ```
> :- set_prolog_flag(suspicious_warning, off).
> :- include('$LOGTALKHOME/integration/logtalk_comp_gp.pl').
> :- include('$LOGTALKHOME/adapters/gnu.pl').
> :- include('$LOGTALKHOME/paths/paths.pl').
> :- set_prolog_flag(suspicious_warning, on).
> ```
> 
> NB2: I had to put the `include('logtalk_comp_gp.pl')` first (while it is consulted last), else I had a compilation warning:
> 
> ```
> In file included from logtalk_gp_new.pl:29
>                  from $LOGTALKHOME/integration/logtalk_comp_gp.pl:26
> $LOGTALKHOME/core/core.pl:191: warning: directive occurs after definition of logtalk_library_path/2 - directive ignored
> ```

The warning seems to be due to the `core.pl` file containing the multifile directive for this predicate but no clauses for it. The `paths.pl` file contain both. A `gplc` issue or limitation in the handling of `multifile/1` directives?

> To test with this `logtalk_gp_new.pl` (before replacing existing `logtalk_gp.pl`), modify `gplgt.sh`:
> 
> ```
> #exec gprolog --entry-goal "['\$LOGTALKHOME/integration/logtalk_gp.pl']" "$@"
> exec gprolog --entry-goal "['\$LOGTALKHOME/integration/logtalk_gp_new.pl']" "$@"
> ```
> 
> With this inclusions all tests work well (i.e. as previously and with same timing).

That should indeed be the case.

> ### Solution 1: compile for byte-code
> This can be done with:
> 
> ```
> gplc -w logtalk_gp_new.pl
> ```
> 
> This creates a file `logtalk_gp_new.wbc` which can be loaded with `load/1` built-in.
> 
> Modify `gplgt.sh` replacing `consult/1` by `load/1`:
> 
> ```
> #exec gprolog --entry-goal "['\$LOGTALKHOME/integration/logtalk_gp.pl']" "$@"
> #exec gprolog --entry-goal "['\$LOGTALKHOME/integration/logtalk_gp_new.pl']" "$@"
> exec gprolog --entry-goal "load('\$LOGTALKHOME/integration/logtalk_gp_new.wbc')" "$@"
> ```
> 
> With this, the whole test is around 33% faster:
> 
> ```
> % 186 test sets: 175 completed, 9 skipped, 2 broken, 0 timedout, 0 crashed
> % 3138 tests: 97 skipped, 2918 passed, 123 failed (0 flaky)
> real	3m33.545s
> user	2m51.542s
> sys	0m34.623s
> ```
> 
> ### Solution 2: compile to native-code
> A new top-level called `gplgt_native` including logtalk code should be obtained with:
> 
> ```
> gplc -o gplgt_native --new-top-level logtalk_gp_new.pl
> ```
> 
> But this reveals a problem:
> 
> ```
> Undefined symbols for architecture arm64:
>   "predicate('$logtalk#0.print_message#3'/4)", referenced from:
> ```
> 
> It seems that `'$logtalk#0.print_message#3'/4` is created in a temporary file/folder (I could not find its definition with grep, I only found it is invoked in `core/core.pl`). I fixed it by surrounding the 2 invocations in `core.pl` with `call/1`:
> 
> ```
> 619c619
> < 	'$logtalk#0.print_message#3'(comment(debugging), debugger, logtalk_debugger_aborted, ExCtx).
> ---
> > 	call('$logtalk#0.print_message#3'(comment(debugging), debugger, logtalk_debugger_aborted, ExCtx)).
> 6729c6729
> < 		'$logtalk#0.print_message#3'(Kind, core, Message, ExCtx)
> ---
> > 		call('$logtalk#0.print_message#3'(Kind, core, Message, ExCtx))
> ```

This fix is not an option that I'm willing to apply to the `core.pl` file. The solution here is to use the provided embedding script that I mentioned in my previous reply.

> The compilation is now OK:
> 
> ```
> gplc -o gplgt_native --new-top-level logtalk_gp_new.pl
> ```
> 
> NB: I suppose the adequate way to solve this is to add a `multifile/1` directive in `core.pl` (easy) but also in the temporary file created in `scratch/` (more difficult for me):
> 
> ```
> :- multifile('$logtalk#0.print_message#3'/4).
> ```
> 
> Anyway, this creates a new top-level, run it with:
> 
> ```
> ./gplgt_native
> ```

The embedding script can be used to create a new GNU Prolog + Logtalk top-level without those hacks.

> This file should act exactly as `gplgt.sh`, so we can now modify `gplgt.sh` as follows:
> 
> ```
> #exec gprolog --entry-goal "['\$LOGTALKHOME/integration/logtalk_gp.pl']" "$@"
> #exec gprolog --entry-goal "['\$LOGTALKHOME/integration/logtalk_gp_new.pl']" "$@"
> #exec gprolog --entry-goal "load('\$LOGTALKHOME/integration/logtalk_gp_new.wbc')" "$@"
> exec "$LOGTALKHOME/integration/gplgt_native" "$@"
> ```
> 
> With this, the whole test time is divided by 2:
> 
> ```
> % 186 test sets: 175 completed, 9 skipped, 2 broken, 0 timedout, 0 crashed
> % 3138 tests: 97 skipped, 2918 passed, 123 failed (0 flaky)
> real	2m55.230s
> user	2m18.015s
> sys	0m30.221s
> ```
> 
> ### Conclusion
> It is easy to improve, logtalk for gprolog (the inclusion vs consult can be done for other systems). I would be in favor of let the user chose which version it wants, e.g. modifying the script `gplgt.sh` to accept an additional argument (default=consult or `bc`for byte-code or `nc` for native code). Another possibility is to proved 3 scripts.

That would require the compilation to byte code or native code to be done **once** to be effective, ideally during installation or when updating the Logtalk git repo clone. But that rises some complications. E.g. installation can happen running a manual installation script or using one of the provided installers. Also, any solution should work the same for both POSIX and Windows systems.

> Then modify `logtalk_tester.sh` to accept one of the 3 above (e.g. `-p gnu`, `-p gnu_bc`, `-p gnu_nc` or any other option).

That's far easier. It only requires deciding on the name of the native `gplgt` version.

**Comment by pmoura** [comment]
Testing your suggestion for the `logtalk_gp.pl` shows that the changed file order breaks settings files (which are used to override default flag values). The correct order is:

```logtalk
:- set_prolog_flag(suspicious_warning, off).
:- built_in.
:- include('$LOGTALKHOME/adapters/gnu.pl').
:- include('$LOGTALKHOME/paths/paths.pl').
:- include('$LOGTALKHOME/core/core.pl').
:- set_prolog_flag(suspicious_warning, on).
```

But, as you mentioned, then compilation to native code fails with errors.

P.S. The relevant test set here is `logtalk3/tests/logtalk/settings`.

**Comment by pmoura** [comment]
I'm happy to change the `logtalk_gp.pl` file to use `include/1` directives. But the fix for the compilation to native code error is in the GNU Prolog side (in the handling of `multifile/1` directives). To be clear, breaking settings files functionality is not an option.

**Comment by didoudiaz** [comment]
Obviously ! I keep you informed when I make some progress on this.

**Comment by pmoura** [comment]
> BTW, the executable is not standalone and needs logtalk Prolog code be around.

Not sure I understand. Are you referring to the executable generated by the current embedding script? I can delete all the Logtalk code from its install location and the executable still works fine. And its startup time is noticeably faster than the `gplgt` integration script.

**Comment by didoudiaz** [comment]
I just tested the embedding feature and it woks very well. I followed example in ../SCRIPT.txt I and the 'logtalk' executable generated is standalone. It starts must faster. How can I use it to run the tests ? I tried to simply modified `gplgt.sh`:
```
#exec gprolog --entry-goal "['\$LOGTALKHOME/integration/logtalk_gp.pl']" "$@"
exec $HOME/collect/logtalk "$@"
```
But this does not work.

BTW: can you rapidly explain me what does the script ? (I tried to understand how it works: it seems important files are copied in a tmp dir (e.g. `core.pl`), I suppose others are generated in this tmp dir. I also seen several `logtalk_compile`, what is the result of the logtalk compilation ? What is the difference between what I did in my experiments and what the script does (both generated a native executable) ?

**Comment by pmoura** [comment]
> I just tested the embedding feature and it woks very well. I followed example in ../SCRIPT.txt I and the 'logtalk' executable generated is standalone.

Thanks for confirming. Btw, is there a way to check if a `gplc` generated executable have any dependency in some external Prolog code?

> It starts must faster. How can I use it to run the tests ? I tried to simply modified `gplgt.sh`:
> 
> ```
> #exec gprolog --entry-goal "['\$LOGTALKHOME/integration/logtalk_gp.pl']" "$@"
> exec $HOME/collect/logtalk "$@"
> ```
> 
> But this does not work.

The `logtalk_tester.*` scripts will need to be modified to accept an alternative to `-p gnu`. I will look into it.

> BTW: can you rapidly explain me what does the script ? (I tried to understand how it works: it seems important files are copied in a tmp dir (e.g. `core.pl`), I suppose others are generated in this tmp dir. I also seen several `logtalk_compile`, what is the result of the logtalk compilation ? What is the difference between what I did in my experiments and what the script does (both generated a native executable) ?

A small part of Logtalk (the built-in objects, protocols, and categories) is implemented in Logtalk itself. Thus, calls to the `logtalk_compile/2` predicate are used to compile those Logtalk source files into intermediate Prolog code, which is then combined with the Prolog code for the compiler/runtime and the backend adapter file (and optionally the intermediate  Prolog code generated from a Logtalk application). The `logtalk_compile/2` predicate differs from the `logtalk_load/2` predicate in that it compiles to disk instead of both compiling to disk and loading the resulting Prolog files.

**Comment by didoudiaz** [comment]
> Btw, is there a way to check if a gplc generated executable have any dependency in some external Prolog code?

You can test if there is a a dependencies at the native executable level (dynamic libs) with ldd (or otool -L on mac). There is no dependencies on Prolog files, except if the Prolog compiled code does itself consult/1, load/1 (or any other file reading).

> The logtalk_tester.* scripts will need to be modified to accept an alternative to -p gnu. I will look into it.

That would be great !

> A small part of Logtalk (the built-in objects, protocols, and categories) is implemented in Logtalk itself. Thus, calls to the logtalk_compile/2 predicate are used to compile those Logtalk source files into intermediate Prolog code, which is then combined with the Prolog code for the compiler/runtime and the backend adapter file (and optionally the intermediate Prolog code generated from a Logtalk application). The logtalk_compile/2 predicate differs from the logtalk_load/2 predicate in that it compiles to disk instead of both compiling to disk and loading the resulting Prolog files.

Nice piece of work. Really

**Comment by pmoura** [comment]
Thanks. Btw, can you take a look to the "Known issues" section in the https://github.com/LogtalkDotOrg/logtalk3/blob/master/scripts/embedding/gprolog/NOTES.md file and let me know if anything there is now outdated?

**Comment by pmoura** [comment]
I'm testing with changes to the `logtalk_tester.sh` script that support:

```bash
$ logtalk_tester -p gnunative
```

This assumes a `gplgt_native` executable in the system `PATH` that was generated using:

```bash
$ ./gprolog_embed_logtalk.sh -c -d ~/collect
```

This new executable works fine and I can load applications and run tests from its top-level. But it doesn't work when called from the `logtalk_tester.sh` script. The problem seems to be that the script calls the executable using the `--query-goal` option. But the option seems to not be available. What am I missing?

**Comment by pmoura** [comment]
Solved using:

```text
$ ./gprolog_embed_logtalk.sh -c -d ~/collect -- --new-top-level
```

**Comment by pmoura** [comment]
https://github.com/LogtalkDotOrg/logtalk3/commit/9999ebc6b9181d6fc5c732a65b1413b1281718ef

**Comment by didoudiaz** [comment]
Exactly, pass `--new-top-level` to act as a new top-level (and thus recognize top-level options). 
We can even then add `-n` to name the executable and pass `gplc` option to avoid suspicious warning:
```
./gprolog_embed_logtalk.sh -c -n gplgt_native  -d ~/collect -- --new-top-level --no-susp-warn
```
However, `logtalk_tester .sh -p gnunative` does not yet work.

**Comment by pmoura** [comment]
In the above commit I went with shorter names: `gnunc` and `gplgtnc`.

**Comment by didoudiaz** [comment]
Works perfectly ! Thanks.

A (minor) suggestion: you could extend the system allowing `logtalk_tester.sh` `-p` option of the form _system_[`_`_variant_] which would invoke: 

1. _system_`lgt.sh` if there is no variant part.
2. _system_`_`variant_ if there is a variant.

This will simplify (future) use of other embedded systems by `logtalk_tester.sh`:

For gprolog we could have:

`-p gp` invoking `gplgt.sh` as now (no change)
`-p gp_nc` invoking `gplgt_nc` (small change)
and even
`-p gp_bc` invoking `gplgt_bc` (if one day we want to handle a pre-compiled version for byte-code)

This requires a bit change for gprolog: `-p gnu` becoming `-p gp` (`gnu` is not a good idea since `gnulgt` is a bit confusing).

Do you think it is useful ?

**Comment by pmoura** [comment]
System identifiers were taken from the names of the Prolog systems minus the word Prolog. Thus `gnu`, `swi`, `trealla`, ... Same identifiers are use for the Logtalk `prolog_dialect` flag values. I see no sufficient reason here to break backwards compatibility.

**Comment by didoudiaz** [comment]
OK. I then summarize (on a Unix-like system):

Create a gprolog native executable called `gplgtnc` thanks to [logtalk embedding](https://github.com/LogtalkDotOrg/logtalk3/tree/master/scripts/embedding/gprolog) capabilities and copy/link it under a directory of the `PATH`:
```
$ cd $LOGTALKHOME/scripts/embedding/gprolog
$ ./gprolog_embed_logtalk.sh -c -n gplgtnc  -d ~/collect -- --new-top-level --no-susp-warn
$ ln -s ~/collect/gplgtnc SOME_DIR_OF_PATH
```
Use it to execute the tests:
```
$ cd $LOGTALKHOME/tests/prolog
$ logtalk_tester.sh -p gnunc
```
Thanks again

**Comment by pmoura** [comment]
Also explained in the updated `man` file.

Thanks for your feedback and help.
