### ISSUE TITLE
SWI-Prolog "pack" installation needs chmod +x to become functional

### ISSUE THREAD

**Issue by hackst8r** [LogtalkDotOrg/logtalk3#17]
From SWI-Prolog, install logtalk with 

| ?- pack_install(logtalk).

The following shell commands are needed to fixup the installation and make the sh scripts executable:

logtalk_dir="$HOME/lib/swipl/pack/logtalk/logtalk-3.00.1"
(cd "$logtalk_dir/scripts" && chmod +x *.sh)
(cd "$logtalk_dir/integration" && chmod +x *.sh)

**Comment by pmoura** [comment]
In the pack archive, all scripts are executable. It seems that the SWI-Prolog `archive` library, used for extracting the archive files, clears the executable permission. Thanks for bringing this issue to my attention. I will look into it.

**Comment by pmoura** [comment]
The SWI-Prolog developer have confirmed that the `archive` library will need to be updated to preserve file executable permission. Until then, I added a note at the end to the pack `README.md` file:

https://github.com/LogtalkDotOrg/logtalk3/blob/master/scripts/pack/logtalk/README.md

**Comment by pmoura** [comment]
Fixed in SWI-Prolog 7.3.29.
