### ISSUE TITLE
Unable to run SWI Prolog code in a Logtalk object

### ISSUE THREAD

**Issue by Jonathon-Doran** [LogtalkDotOrg/logtalk3#177]
I have been wanting to query ChatGPT from Logtalk for some time, and finally got around to looking into it.  But I am running into problems.  This is almost certainly a user error on my part, but I've done everything that I can think of to try to figure out what is going on.

I asked on the SWI forums and was directed to some code Jan Wielemaker posted on the SWI Prolog forums that did exactly what I wanted, and I've attached it below for reference.

I made some basic changes to try to get it to run under Logtalk, and am frustrated. At first I figured that the JSON was not properly formatted, but I see that it is essentially the same as the JSON produced under SWI Prolog (dictionary members are in a slightly different order).  I went down this rabbit hole since a GITHUB project which did something similar worked fine for some models failed on other.  (I concluded that this was probably due to the JSON format).

When I run a query, I just get back "false".    A trace isn't helping me because failures occur too deep into the call to provide any meaning (to me).

Here is the syntax for the SWI Prolog query:
query_gpt(_{query: "Which member of the Golden Girls cast was the hottest?"}, Reply).

Here is the syntax for the Logtalk query:
gpt_utils::query_gpt(_{query: "Are llamas good to eat?"}, Reply).

Files renamed because Prolog/Logtalk code not supported upload types...

SWIPL code:
[demo.pl.txt](https://github.com/LogtalkDotOrg/logtalk3/files/12197146/demo.pl.txt)

Logtalk Code
[gpt.lgt.txt](https://github.com/LogtalkDotOrg/logtalk3/files/12197229/gpt.lgt.txt)
[loader.lgt.txt](https://github.com/LogtalkDotOrg/logtalk3/files/12197232/loader.lgt.txt)

**Comment by pmoura** [comment]
I cannot reproduce the problem as I don't have an OpenAI key. That said, my advice is to avoid using SWI-Prolog proprietary dicts as there are problems with their implementation when used in Logtalk code. Something like:

```logtalk
:- object(gpt_utils).

	:- use_module(http_client, [http_get/3, http_post/4]).
	:- uses(json, [generate/2])
	:- uses(reader, [line_to_codes/2]).

	:- public(query_gpt/3).

	get_key(Key) :-
		setup_call_cleanup(
			open(key, read, In),
			line_to_codes(In, Key),
			close(In)
		).

	query_gpt(Query, Reply, Status) :-
		get_key(Key),
		Url = 'https://api.openai.com/v1/chat/completions',
		generate(
			codes(Data),
			{	model - 'gpt-3.5-turbo',
				temperature - 0.7,
				messages - {
					role - user,
					content - Query
				}
			}
		),
		http_post(
			Url,
			codes(Data),
			Reply,
			[
				authorization(bearer(Key)),
				status_code(Status),
				to(atom)
			]
		).

:- end_object.
```

You'll also need to modify the `loader.lgt` file to include:

```logtalk
	logtalk_load(json(loader)),
	logtalk_load(reader(loader)),
```

**Comment by Jonathon-Doran** [comment]
Thanks, I'll give it a shot.  And if necessary will somehow arrange to get you an API key.

**Comment by Jonathon-Doran** [comment]
Hmm..

?- gpt_utils::query_gpt(_{query: "Tell me a story"}, Reply, Status).
!     Domain error: value codes(A) is not in domain json_sink
!       in goal: generate(codes(A),{model-'gpt-3.5-turbo',temperature-0.7,messages-{role-user,content-B{query:"Tell me a story"}}})
!       with execution context:
!         entity:            json(curly,dash,atom)
!         sender:            gpt_utils
!         this:              json(curly,dash,atom)
!         self:              json
!         meta-call context: []
!         coinduction stack: []

I interpret that as not liking the Data.

**Comment by pmoura** [comment]
You need to pass the query as an atom as dicta are no longer used.

**Comment by pmoura** [comment]
Try `gpt_utils::query_gpt({query - 'Tell me a story'}, Reply, Status).`

**Comment by Jonathon-Doran** [comment]
That made a big improvement, thanks.  I am talking to their server now.
The key needs to be a string, not codes.  And I think that holds true for the JSON.  I changed get_key back to                       
                         open(key, read, In),
                        read_line_to_string(In, Key),
                        close(In)

and I can now authenticate.  But the data is not being recognized.  For example it says

Reply = '{\n    "error": {\n        "message": "you must provide a model parameter",\n        "type": "invalid_request_error",\n        "param": null,\n        "code": null\n    }\n}\n',
Status = 400.

**Comment by Jonathon-Doran** [comment]
Neither atom nor string seemed to make it happy.  Now the post is just failing.  At least codes allowed it to succeed far enough to generate an HTML response.

**Comment by pmoura** [comment]
See the documentation of the Logtalk `json` library: https://logtalk.org/manuals/libraries/json.html

**Comment by Jonathon-Doran** [comment]
The problem is that I have no idea of what this thing wants.  The SWI documentation indicates a number of things one can post, but that doesn't mean the GPT server will accept them.

I tried a parsed JSON term, atom, chars, codes.  The codes and atom both were accepted by the server, but the error was that I didn't provide a model parameter.  That is in the data, so there must be a coding issue.

I tried form and form_data, but they are not in domain json_sink.

I need to get busy grading exams, so I think playtime is over for now.  Thanks for looking at this.

**Comment by pmoura** [comment]
Fixed an error above for the `messages` key: its value must be a list.

**Comment by Jonathon-Doran** [comment]
GPT isn't even seeing the model parameter (which is a peer to messages).  I applied the fix to messages, but it doesn't change the behavior

Reply = '{\n    "error": {\n        "message": "you must provide a model parameter",\n        "type": "invalid_request_error",\n        "param": null,\n        "code": null\n    }\n}\n',
Status = 400.

**Comment by pmoura** [comment]
Using the key you sent me and the following code works.

`loader.lgt` file:

```logtalk
:- initialization((
	use_module(library(http/http_open)),
	use_module(library(http/http_client)),
	use_module(library(http/json)),
	use_module(library(ssl)),
	logtalk_load(json(loader)),
	logtalk_load(reader(loader)),
	logtalk_load(gpt)
)).
```

`gpt.lgt` file:

```logtalk
:- object(gpt).

	:- use_module(http_client, [http_get/3, http_post/4]).
	:- uses(json, [generate/2]).
	:- uses(reader, [line_to_codes/2]).

	:- public(query/3).

	get_key(Key) :-
		setup_call_cleanup(
			open(key, read, In),
			(line_to_codes(In, KeyCodes), atom_codes(Key, KeyCodes)),
			close(In)
		).

	query(Query, Reply, Status) :-
		get_key(Key),
		Url = 'https://api.openai.com/v1/chat/completions',
		generate(
			codes(Data),
			{	messages - [{role - user, content - Query}],
				model - 'gpt-3.5-turbo',
				temperature - 0.7
			}
		),
		http_post(
			Url,
			codes('application/json', Data),
			Reply0,
			[
				authorization(bearer(Key)),
				status_code(Status),
				to(codes)
			]
		),
		parse(codes(Reply0), Reply).

:- end_object.
```

For example:

```text
$ swilgt -q
?- {loader}.
true.

?- gpt::query('Are llamas good to eat?', Reply, Status), writeq(Reply).
{id-'chatcmpl-7hYmQnYqA2JVho2AQHsowRuzKwYmy',object-'chat.completion',created-1690616154,model-'gpt-3.5-turbo-0613',choices-[{index-0,message-{role-assistant,content-'Yes, llamas can be eaten, and their meat is consumed in some parts of the world, particularly in South America. Llama meat is considered lean and nutritious, similar to other red meats like beef or lamb. However, it is important to note that llamas are more commonly valued for their wool, pack-carrying ability, and as companion animals rather than for their meat.'},finish_reason-stop}],usage-{prompt_tokens-14,completion_tokens-78,total_tokens-92}}
Reply = {id-'chatcmpl-7hYmQnYqA2JVho2AQHsowRuzKwYmy', object-'chat.completion', created-1690616154, model-'gpt-3.5-turbo-0613', choices-[{..., ...}], usage-{... - ..., ..., ...}},
Status = 200.
```

**Comment by Jonathon-Doran** [comment]
Thanks a lot.  I'm going to need to study this a lot to see what the differences are.  This was very frustrating for me, and I'm disappointed that I couldn't figure it out on my own.  But words cannot express how grateful I am for your assistance with this.

I am curious what your thought process was debugging this was.  How did you figure it out?  There is precious little useful feedback when things go wrong.  I would very much like to learn as much as possible from this  experience.

**Comment by pmoura** [comment]
In your original porting attempt, I think the query was failing in the `Reply = Reply0.put(status, Status)` goal due to the compatibility issue I mentioned with dicts.

In the working solution above, I initially missed the required `'application/json'` request header. The hint was the error reply from the OpenAI services as consulting their API documentation showed the constructed JSON request to be correct.
