### ISSUE TITLE
os::full_device_path/1 is incorrect

### ISSUE THREAD

**Issue by infradig** [LogtalkDotOrg/logtalk3#178]
Whether by design or otherwise `os::full_device_path/1` is currently returning `/dev/null` when it should be `/dev/full`.

**Comment by pmoura** [comment]
Thanks for noticing. Tired eyes and too much multitasking. Fixed now. Unfortunately, it seems that most Prolog systems fail to correctly handle errors from devices.

**Comment by infradig** [comment]
SWI and Trealla (at least) only fail on the close. The writes don't
generate a testable error at least on Linux.

**Comment by infradig** [comment]
Itl seems adding a fflush() call to nl/1 was enough to trigger it. Makes
sense.

**Comment by pmoura** [comment]
> SWI and Trealla (at least) only fail on the close. The writes don't generate a testable error at least on Linux.
> […](#)

Yes, that's one of the main issues. Makes sense to only get an error when the output is flushed. With the latest Trealla Prolog version:

```text
$ tplgt
...
Trealla Prolog (c) Infradig 2020-2023, v2.23.38
?- catch((open('/dev/full', write, S), write(S, foo), close(S)), E, true).
   E = error(io_error('No space left on device','<$stream>'(4)),close/1).
```

A lack of space error is indeed the expected error. Unfortunately, the ISO standard fails to specify the exact exception that should be throw in this case.
