### ISSUE TITLE
create_object hides exception cause

### ISSUE THREAD

**Issue by unthingable** [LogtalkDotOrg/logtalk3#212]
An exception thrown during `create_object` is missing critical source information like trace and location.

A TL;DR of example DX:

```logtalk
!     load_data: failure (in 0.026040000/0.032000000 cpu/wall seconds)
!       test goal throws an error but should have succeeded: error(syntax_error(operator_expected),logtalk(create_object(data_file,[imports([data_filec,hooked_loader(my_hook)])],[(initialization::include('test/data.pl'))],[path('test/data.pl')]),c(data_loader,data_loader,r(file,data_loader,[],[]))))
!       in file /Users/.../tests.lgt between lines 156-158
```
A test fails, points at a problem line, says there was a `create_object` somewhere that couldn't succeed. It leaves some clues to find it but doesn't say exactly where that `create_object` is.

With a bit of effort I find the `create_object` call and invoke it directly, hoping it might give a more detailed message and get me closer to the root of the problem:

```logtalk
?- data_loader::load(data_file,'test/data.pl').
% Calling: create_object(data_file, [imports([data_filec, hooked_loader(my_hook)])], [(initialization::include('test/data.pl'))], [path('rulesets/nda1-wtf.pl')]).
!     Syntax error: operator_expected
!       in goal: call(create_object(data_file,[imports([data_filec,hooked_loader(my_hook)])],[(initialization::include('test/data.pl'))],[path('test/data.pl')]))
!       with execution context:
!         entity:            data_loader
!         sender:            user
!         this:              data_loader
!         self:              data_loader
!         meta-call context: []
!         coinduction stack: []
!     
```

Nope, still nothing about where this happened. Meanwhile, the real problem was here:

```logtalk
:- category(hooked_loader(_Hook_)).
    ...
    include(Path) :-
        reader::file_to_terms(Path, Terms), % <--
        meta::map(load_term, Terms).
:- end_category.
```

It was reading a file with nonstandard operators and was missing the corresponding declared `op`.

The guesswork would have been unnecessary if the original error said something like:
```logtalk
!       test goal throws an error but should have succeeded: error(syntax_error(operator_expected)...
!       in file .../tests.lgt between lines 156-158
!       in file <data_loader> between lines <load predicate>
!       in file <hooked_loader> at line <reader::file_to_terms>
```

Or even this, like one can get with regular exceptions. Even though it doesn't list the original locations in source .lgt, there is enough information to know where to look (`'$data_filec#0.stats#1'`).
```logtalk
[debug]  ?- data_file::stats(R).
ERROR: Unknown error term: foo
ERROR: In:
ERROR:   [19] throw(error(foo,_155014))
ERROR:   [18] '$lgt_debug'(goal(throw(...),throw(...)),c(data_file,data_filec,r(user,data_file,[],[]))) at /usr/local/share/logtalk/core/core.pl:6755
ERROR:   [17] '$data_filec#0.stats#1'(_155108,c(data_file,data_filec,r(user,data_file,[],[]))) at /Users/.../.lgt_tmp/file_5686231_8519_lgt.pl:186
ERROR:   [16] '$lgt_debug'(goal(stats(_155170),'$data_filec#0.stats#1'(_155174,...)),c(data_file,data_filec,r(user,data_file,[],[]))) at /usr/local/share/logtalk/core/core.pl:6755
ERROR:   [15] '$lgt_send_to_obj_ne_'(data_file,stats(_155224),c(user,user,r(user,data_file,[],[])))1-st clause of ::/2 (event transparent) <no source>
ERROR:   [14] '$lgt_debug'(top_goal(data_file:: ...,'$lgt_send_to_obj_ne_'(data_file,...,...)),c(user,user,r(user,data_file,[],[]))) at /usr/local/share/logtalk/core/core.pl:6751
ERROR:   [13] catch(user:'$lgt_debug'(...,...),error(foo,context(_155368,_155370)),user:'$lgt_runtime_error_handler'(...)) at /usr/local/Cellar/swi-prolog/HEAD-f146a50/lib/swipl/boot/init.pl:565
ERROR:   [12] data_file::stats(_155416) at /usr/local/share/logtalk/core/core.pl:560
ERROR:   [11] toplevel_call(user:user: ...) at /usr/local/Cellar/swi-prolog/HEAD-f146a50/lib/swipl/boot/toplevel.pl:1317
^  Exception: (4) setup_call_cleanup('$toplevel':notrace(call_repl_loop_hook(begin, 0)), '$toplevel':'$query_loop'(0), '$toplevel':notrace(call_repl_loop_hook(end, 0))) ? Unknown option (h for help)
```

I'm hoping it is possible to either simply enable this kind of stack trace in the output or get at the exception cause some other way, and I'm just too blind to see it. If not, the masking of the cause is IMO a serious problem hindering development.

**Comment by unthingable** [comment]
I noticed SWI-Prolog doesn't keep that information either, but it did produce that example trace with debug enabled (swipl native, enabled via `?- debug.`). `debugger::debug` didn't have that effect, I wonder if it could.

Perhaps the trace could be collected optionally and at least printed where exception is being rethrown in `create_object` if debug mode is on?

**Comment by pmoura** [comment]
> I noticed SWI-Prolog doesn't keep that information either, but it did produce that example trace with debug enabled (swipl native, enabled via `?- debug.`). `debugger::debug` didn't have that effect, I wonder if it could.

I'm not sure that could work. For debugging Logtalk applications, you need to use the Logtalk debugger. Prolog backend own debuggers are not Logtalk aware. In your particular case, calling SWI-Prolog own `debug/0` predicate seems to allow some useful information to be kept (instead of optimized away). But that doesn't mean that Logtalk is able to (re)use that information, as I explained above.

> Perhaps the trace could be collected optionally and at least printed where exception is being rethrown in `create_object` if debug mode is on?

Tricky. The Logtalk debugger is a regular application written using the reflection API. See:

https://logtalk.org/manuals/userman/debugging.html#debug-and-trace-events

Those two reflection API predicates do not provide an easy way to keep/maintain the trace in parallel with normal or debug execution. You would need some sort of meta-interpreter.

The easiest solution to understand an unexpcted failure or exception is still to use the Logtalk debugger to generate a trace. Note that it can be configure to not stop at each port using `debugger::leash(none)`.

**Comment by unthingable** [comment]
Thank you for the explanation, I think this will be enough to navigate these issues.
