### ISSUE TITLE
Dead code scanner mistargets predicates called by meta::map

### ISSUE THREAD

**Issue by unthingable** [LogtalkDotOrg/logtalk3#214]
![image](https://github.com/LogtalkDotOrg/logtalk3/assets/925755/df7869d0-f882-4e97-8bc5-456b3896ce5c)

Logtalk 18ea2f9

Code for reference:
```logtalk
:- category(hooked_loader(_Hook_)).

    load_term(Term) :-
        _Hook_::expand_term(Term, Term1),
        assertz(Term1).

    :- protected(include/1).
    include(Path) :-
        reader::file_to_terms(Path, Terms),
        meta::map(load_term, Terms).

:- end_category.
```

**Comment by pmoura** [comment]
See documentation:
https://logtalk.org/manuals/devtools/dead_code_scanner.html#caveats

**Comment by unthingable** [comment]
Also with compile directives (`arg_type` is called in meta::map on line 106)

![image](https://github.com/LogtalkDotOrg/logtalk3/assets/925755/2a0ea886-8bdb-440a-ab65-115a943a0c17)

**Comment by unthingable** [comment]
> See documentation: https://logtalk.org/manuals/devtools/dead_code_scanner.html#caveats

Ah, missed that, thanks. Not a new issue then.

**Comment by pmoura** [comment]
Note that you can use the `logtalk_make/1` predicate (or its tope-level shortcuts) to quickly recompile code in debug/normal/optimal mode:
https://logtalk.org/manuals/refman/predicates/logtalk_make_1.html
