### ISSUE TITLE
Module arbitrary untested?

### ISSUE THREAD

**Issue by jburse** [LogtalkDotOrg/logtalk3#25]
Hi,

I find:

```
    arbitrary(object, Arbitrary) :-
		findall(Object, current_object(Object), Objects),
		member(Arbitrary, Objects).

	arbitrary(protocol, Arbitrary) :-
		findall(Protocol, current_object(Protocol), Protocols),
		member(Arbitrary, Protocols).

	arbitrary(category, Arbitrary) :-
		findall(Category, current_category(Category), Categories),
		member(Arbitrary, Categories).
```
Two things here: 
1) I find the findall/3 and member/2 combination redundant. 
2) second I guess it should say current_protocol(Prolocol) and not current_object(Protocol).

So I guess the better code would be:

```
    arbitrary(object, Arbitrary) :-
		current_object(Arbitrary).

	arbitrary(protocol, Arbitrary) :-
		current_protocol(Arbitrary).

	arbitrary(category, Arbitrary) :-
		current_category(Arbitrary).
```

**Comment by pmoura** [comment]
`arbitrary`is a category, not a module. Note that above `member/2` is from the `random` library. Your suggestion would result in protocols being returned in loading order instead of random order. Fixed the typo in the current git version. Thanks for the bug report.

**Comment by jburse** [comment]
Ok, very interesting. 

Now I understand, wanted to suggest to remove more member/2 uses.
How do you deal with a name clash, using list member and random member
in same Prolog code. Wouldn't it make more sense to use different names.

Random isn't an object. If it were an object and if arbitrary were also an
object, we could plug it into arbitrary. For example concurrent threads 
could use their own random sequence streams. 

I don't think your current category design of arbitrary and random allows
to plugin random. If you can plugin, you can do things like below. On a
4 core/8 hyperthread machine you Quick Check would run 4-8 times faster:

Package `parallel'. R-core December 4, 2015
https://stat.ethz.ch/R-manual/R-devel/library/parallel/doc/parallel.pdf
(See section 6 Random-number generation)

Generally I have the feeling the potential of Logtalk is not enough used.
Much of the libraries you have recently released, the unicode stuff etc..,
is not object oriented. We could also use ordinary Prolog modules.

You should **show case** both the threaded library and the possibility
to provide objects of Logtalk much more. In case of Jekejeke Prolog
I am currently busy with a new module "distributed", which adresses
only the threaded stuff.

The predicate horde/[2,3] of the new module "distributed" could be used 
to run parallel threads with partitioned random streams. But I didn't try it yet. 
Note the difference in your threaded/1 and the horde/[2,3]. We do the
thread replication automatically, your threaded/1 doesn't provide that.

An alternative to objects would be to have down in the low level, on the 
interpreter engine level, a random generator instance per interpreter that 
can be sufficiently configured. But if you don't use your own objects, you
have a dependency on the Prolog vendor and his Prolog system.

Bye

**Comment by pmoura** [comment]
Predicate name clashes are easily solved using either the `uses/2` directive to define aliases or by using `::/2`. No idea why you're talking about "in same Prolog code". This is Logtalk. Reusing names makes APIs simpler to learn and consistent. It's a common practice in OOP.

`random` is a library object and provides a fully portable threads aware implementation. It also supports independent random generators, each own with its own seed. The `arbitrary` category is user-extensible (as noted in the release notes). Consult the documentation.

**Comment by jburse** [comment]
Yes, but the uses of random in arbitrary, even if random itself implements some protocol 
randomp, is hardwired in arbitrary.

To make it plugable, you need to only refer to randomp in arbitrary and allow to
plugin some randomp object such as random.

I see this not from the documentation, but from the source code. I assume documentation
says the same as the source code. Right?

**Comment by jburse** [comment]
I don't think an end-user can implement a derivation from arbitary, that can
influence the uses/1 used inside arbitrary. How should this work?

Documentation of uses/1 says, that a module prefix is shortened:

Before:
:- list::append(A, B, C),

After:
:- uses(list, [append/3]).
:- append(A, B, C),

Is this done via late binding? Can a derivid entity change this?

**Comment by pmoura** [comment]
Your questions are outside the scope of this **issue tracker**. Use the discussions forums instead for general discussion on Logtalk programming.
