### ISSUE TITLE
The arbitrary category is not enough user-extensible.

### ISSUE THREAD

**Issue by jburse** [LogtalkDotOrg/logtalk3#26]
I don't see enough OO design in the arbitraty category. Its not possible 
to plugin a random number generator.

Mostlikely the only thing that can be done is exchanging the random.lgt
file. But what if I want one arbitrary to run with random1 and another
arbitrary to run with random2, both random1 and random2 implementing randomp.

Did I overlook something here?

P.S.: I also don't want to exchange arbitrary.lgt, extensibility would mean
that random.lgt and arbitrary.lgt stay as they are.

**Comment by pmoura** [comment]
The `arbitrary` category can be extended by the user to define new arbitrary types. That's required for practical use of `lgtunit` QuickCheck features. Fixing the random number generator allows statically binding to it and fast generation of arbitrary type values, which is important for QuickCheck performance. I don't have a use case for using it with a user-selected random number generator. If you have a need for such functionality, you will need to implement it yourself (or pay someone to implement it for you).

**Comment by jburse** [comment]
So virtual calls are still slow in logtalk? In a typical OO language
one would mind to make the randim number generator plugable 
and have what is now used in arbitrary as random as a default slot value.

The use case I have, I aleady told you, running QuickCheck in parallel
and having more control over the use random number generator. I
assume QuickCheck doesn't only take one sample, right?

**Comment by jburse** [comment]
BTW: Also I must repeat my remark that logtalk should use more
OO. Otherwise one big use case is missing, namely to use the logtalk
language in the first place. 

Why should I use a polymorphic system, if polymorphism is never 
used? So far most of the things that have recently added to logtalk,
unicode, maybe quickcheck, and not worth to switch to logtalk.

I could also use a Prolog with modules. Instead of uses/1 I just
do use_module/1. Where is the business case for logtalk?
