### ISSUE TITLE
Shebang for shell scripts

### ISSUE THREAD

**Issue by dram** [LogtalkDotOrg/logtalk3#36]
When trying to run Logtalk in FreeBSD, several scripts failed with following error:

```
% ./bin/swilgt
bash: ./bin/swilgt: /bin/bash: bad interpreter: No such file or directory
```

It's caused by the unusual location of bash in FreeBSD, which is `/usr/local/bin/bash` instead of `/bin/bash`.

I think there are two approaches to solve this problem:

- change shebang from `#!/bin/bash` to `#!/usr/bin/env bash`
- change scripts to use POSIX confirmed `/bin/sh`

**Comment by pmoura** [comment]
Thanks for the bug report. Fixed in 6b89589 using `#!/usr/bin/env bash`.  Some scripts use bash features and thus it would require more work to use the `/bin/sh` alternative.
