### ISSUE TITLE
Superfluous newline when setting `report' to `warnings'

### ISSUE THREAD

**Issue by dram** [LogtalkDotOrg/logtalk3#37]
Logtalk will output a superfluous newline with following config in `settings.lgt`:

```
:- initialization(set_logtalk_flag(report, warnings)).
```

Run following command:

```
% swilgt.sh -q -t 'write(hi), nl'

hi
%
```

I'm using Logtalk 3.9.3-rc1 and SWI Prolog 7.2.3.

**Comment by pmoura** [comment]
Fixed in c45a3c6. Thanks for the bug report.
