### ISSUE TITLE
Feature Request: loop::foreach/4 (loop over elements with index)

### ISSUE THREAD

**Issue by dram** [LogtalkDotOrg/logtalk3#48]
Currently, Logtalk only has `loop::foreach/3`, which can not be used if element index is needed. It would be nice to have `loop::foreach/4`.

Use cases are similar to Python's `enumerate` function, which are described in [PEP-279](https://www.python.org/dev/peps/pep-0279/). Be aware that Python make use of iterator mechanism instead of extending for loop.

**Comment by pmoura** [comment]
Implemented in 29f37bc84652acdc08d9135d1456e4a82d2231bf.

**Comment by dram** [comment]
Cool, thanks!
