### ISSUE TITLE
`setp` protocol does not document the public predicate `new/1`.

### ISSUE THREAD

**Issue by eazar001** [LogtalkDotOrg/logtalk3#63]
Implementation is simple: 
```
new([]).
```
... yet I could not locate the documentation for it.

**Comment by pmoura** [comment]
Note that the `set`object, besides implementing the `setp` protocol, also inherits from `compound`.
```
?- set::predicate_property(new(_), Property).
Property = logtalk ;
Property = scope(public) ;
Property =  (public) ;
Property = static ;
Property = declared_in(termp) ;
Property = declared_in(termp, 45) ;
Property = defined_in(set) ;
Property = defined_in(set, 141) ;
Property = info([comment('Creates a new term instance (if meaningful).'), argnames(['Term'])]) ;
Property = mode(new(-nonvar), zero_or_one) ;
Property = number_of_clauses(1) ;
Property = number_of_rules(0).
```
Similar for the other object implementing the `setp` protocol, `set/1`:
```
?- set(_)::predicate_property(new(_), Property).
Property = logtalk ;
Property = scope(public) ;
Property =  (public) ;
Property = static ;
Property = declared_in(termp) ;
Property = declared_in(termp, 45) ;
Property = defined_in(set) ;
Property = defined_in(set, 141) ;
Property = info([comment('Creates a new term instance (if meaningful).'), argnames(['Term'])]) ;
Property = mode(new(-nonvar), zero_or_one) ;
Property = number_of_clauses(1) ;
Property = number_of_rules(0).
```

**Comment by eazar001** [comment]
Agreed, and I did indeed trace the documentation all the way down to `termp`. However, the documentation in my opinion could:

A) Be made obvious in the actual protocol
B) Say something specific like ... "creates an empty list to be used with other set operations."

**Comment by eazar001** [comment]
Not critical, but simply a suggested improvement.

**Comment by pmoura** [comment]
The `termp` protocol is implemented by term types that are not lists. Thus, *where* do you suggest to  do A and B? By duplicating the `new/1` predicate declaration in `setp`?

**Comment by eazar001** [comment]
Put that way, it does create a bit of an impasse I suppose.

**Comment by pmoura** [comment]
Closing the issue. Please reopen if you come out with  a proposal to make the documentation more clear while avoiding duplication of code.

**Comment by eazar001** [comment]
Is tying all ancestors of `term` down to a protocol implementing `new/1` useful? Does it make sense to remove `new/1` from the term protocol altogether? Perhaps this is some lack of foresight on my part? (That was admittedly the best idea I could come up with it, though I'm unsure of the ramifications of such a change)
