### ISSUE TITLE
Jekejeke Prolog does not permit Logtalk usage

### ISSUE THREAD

**Issue by jburse** [LogtalkDotOrg/logtalk3#67]
Please note that the Jekejeke Prolog Runtime Library usage is limited to 
"The library can be distributed as part of your applications and libraries 
for execution provided this comment remains unchanged." (*)

Unfortunately the intent here is that the Jekejeke Prolog Runtime Library
does not act as a virtual machine of some sort for a programming language
that is not distant of that of the Jekejeke Prolog Runtime Library.

For the upcoming release 1.3.0 I will try to rephrase more precisely what 
usage is granted and what not. Now your NOTES.txt still refers to version
1.0.4, but there is no such version anymore. So I suggest removing 

jekejeke.pl from the same directory and taking note, that if customers
want a Jekejeke Prolog Runtime Library virtual machine functionality,
for lets say Logtalk, they should contact me at info@xlog.ch .

(*) Example:
https://github.com/jburse/jekejeke-devel/blob/master/jekrun/headless/jekpro/model/builtin/Flag.java

(**) From here:
https://github.com/LogtalkDotOrg/logtalk3/blob/master/adapters/unsupported/NOTES.txt

**Comment by jburse** [comment]
Ok I have adapted the license, it now reads:

>  * Restrictions
>  * Only to be distributed with programs that add significant and primary
>  * functionality to the library. Not to be distributed with additional
>  * software intended to replace any components of the library.

It will take a while until it is seen everywhere on GitHub, 
but Flag.java shows already the clarified license.

**Comment by pmoura** [comment]
Fixed at a67a1ded804cef005de72976e100d40a01d2a371.
