### ISSUE TITLE
Performance metrics for SWI

### ISSUE THREAD

**Issue by thelazydogsback** [LogtalkDotOrg/logtalk3#75]
Just starting to look at LogTalk on SWI.

I see that the Category & Dynamic perf. isn't stellar for SWI.  
The version tested is 7.7.  From the SWI release notes for 8.0:

> Indexing on multiple arguments together, indexing inside compounds, Mode-directed tabling

I'm not sure if LogTalk makes any use of tabling internally, but ISTM that the indexing improvements should help, no?

Has anyone run the perf. tests on 8.x?

thanks

**Comment by pmoura** [comment]
Closing this issue. Reopen if you have further question on performance.
