### ISSUE TITLE
Declaring a predicate as dynamic and incremental requires two declarations

### ISSUE THREAD

**Issue by jamesnvc** [LogtalkDotOrg/logtalk3#77]
Using Logtalk 3.36.0 and SWI-Prolog 8.1.26.

If I have a predicate that will both be dynamic and used in tabled goals, I need to declare it as (in SWI-Prolog), e.g. `:- dynamic(arc/2 as incremental)`. However, it Logtalk, I seem to need to have both `:- dynamic(arc/2)` and `:- dynamic(arc/2 as incremental)`. 
I would expect to only need the second, but if I omit the first, I get errors when retracting/asserting `arc/2` facts, with an error message saying that the predicate isn't dynamic.

**Comment by pmoura** [comment]
That specific syntax variant for the `dynamic/1` directive is not supported in Logtalk 3.36.0 (SWI-Prolog introduced it for  compatibility with XSB). You can use instead the SWI-Prolog `dynamic/2` directive:

```logtalk
:- dynamic([arc/2], [incremental]).
```

I added support for the XSB syntax variant in Logtalk 3.37.0 (6160ce4a430d3ed57e464862bb0fed3ede18e238).

**Comment by pmoura** [comment]
P.S. You can have both 3.36.0 and git versions installed side-by-side and easily switch between them. See https://logtalk.org/running_developer_versions.html

**Comment by jamesnvc** [comment]
Thanks for the quick response Paulo!
