### ISSUE TITLE
Expired Links in the documentation

### ISSUE THREAD

**Issue by kaiser185** [LogtalkDotOrg/logtalk3#99]
In the file:
https://github.com/LogtalkDotOrg/logtalk3/blob/master/manuals/sources/libraries/assignvars.rst

The following link is dead:

http://www.kprolog.com/en/logical_assignment/

I would suggest removing it, or replacing it, for example, with the following copy on the internet archive:

https://web.archive.org/web/20160818050049/http://www.kprolog.com/en/logical_assignment/

Perhaps verifying that no other library contains these types of links is a worthwhile idea, to avoid having anyone run into a potentially malicious site?

**Comment by pmoura** [comment]
Thanks for reporting. About to commit the fix you suggested. To acknowledge you, should I use your user name or your real name? If the later, what's your name?

**Comment by pmoura** [comment]
Fixed in febb66f7a63539ed6f1e4bca731047ea3525c92f.

**Comment by kaiser185** [comment]
> Thanks for reporting. About to commit the fix you suggested. To acknowledge you, should I use your user name or your real name? If the later, what's your name?

the username is fine, thanks for the prompt reaction
